// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessageProto.proto

#ifndef PROTOBUF_ServerMessageProto_2eproto__INCLUDED
#define PROTOBUF_ServerMessageProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_ServerMessageProto_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsLoginMSGImpl();
void InitDefaultsLoginMSG();
void InitDefaultsLoginRSPSImpl();
void InitDefaultsLoginRSPS();
void InitDefaultsRegisterMSGImpl();
void InitDefaultsRegisterMSG();
void InitDefaultsRegisterRSPSImpl();
void InitDefaultsRegisterRSPS();
void InitDefaultsChatMSGImpl();
void InitDefaultsChatMSG();
void InitDefaultsChatRSPSImpl();
void InitDefaultsChatRSPS();
inline void InitDefaults() {
  InitDefaultsLoginMSG();
  InitDefaultsLoginRSPS();
  InitDefaultsRegisterMSG();
  InitDefaultsRegisterRSPS();
  InitDefaultsChatMSG();
  InitDefaultsChatRSPS();
}
}  // namespace protobuf_ServerMessageProto_2eproto
namespace LU {
class ChatMSG;
class ChatMSGDefaultTypeInternal;
extern ChatMSGDefaultTypeInternal _ChatMSG_default_instance_;
class ChatRSPS;
class ChatRSPSDefaultTypeInternal;
extern ChatRSPSDefaultTypeInternal _ChatRSPS_default_instance_;
class LoginMSG;
class LoginMSGDefaultTypeInternal;
extern LoginMSGDefaultTypeInternal _LoginMSG_default_instance_;
class LoginRSPS;
class LoginRSPSDefaultTypeInternal;
extern LoginRSPSDefaultTypeInternal _LoginRSPS_default_instance_;
class RegisterMSG;
class RegisterMSGDefaultTypeInternal;
extern RegisterMSGDefaultTypeInternal _RegisterMSG_default_instance_;
class RegisterRSPS;
class RegisterRSPSDefaultTypeInternal;
extern RegisterRSPSDefaultTypeInternal _RegisterRSPS_default_instance_;
}  // namespace LU
namespace LU {

// ===================================================================

class LoginMSG : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.LoginMSG) */ {
 public:
  LoginMSG();
  virtual ~LoginMSG();

  LoginMSG(const LoginMSG& from);

  inline LoginMSG& operator=(const LoginMSG& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LoginMSG(LoginMSG&& from) noexcept
    : LoginMSG() {
    *this = ::std::move(from);
  }

  inline LoginMSG& operator=(LoginMSG&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginMSG& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoginMSG* internal_default_instance() {
    return reinterpret_cast<const LoginMSG*>(
               &_LoginMSG_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(LoginMSG* other);
  friend void swap(LoginMSG& a, LoginMSG& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LoginMSG* New() const PROTOBUF_FINAL { return New(NULL); }

  LoginMSG* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LoginMSG& from);
  void MergeFrom(const LoginMSG& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LoginMSG* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string username = 2;
  void clear_username();
  static const int kUsernameFieldNumber = 2;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string password = 3;
  void clear_password();
  static const int kPasswordFieldNumber = 3;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // int32 type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LU.LoginMSG)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::int32 type_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsLoginMSGImpl();
};
// -------------------------------------------------------------------

class LoginRSPS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.LoginRSPS) */ {
 public:
  LoginRSPS();
  virtual ~LoginRSPS();

  LoginRSPS(const LoginRSPS& from);

  inline LoginRSPS& operator=(const LoginRSPS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LoginRSPS(LoginRSPS&& from) noexcept
    : LoginRSPS() {
    *this = ::std::move(from);
  }

  inline LoginRSPS& operator=(LoginRSPS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRSPS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoginRSPS* internal_default_instance() {
    return reinterpret_cast<const LoginRSPS*>(
               &_LoginRSPS_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(LoginRSPS* other);
  friend void swap(LoginRSPS& a, LoginRSPS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LoginRSPS* New() const PROTOBUF_FINAL { return New(NULL); }

  LoginRSPS* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LoginRSPS& from);
  void MergeFrom(const LoginRSPS& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LoginRSPS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int32 type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LU.LoginRSPS)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 type_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsLoginRSPSImpl();
};
// -------------------------------------------------------------------

class RegisterMSG : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.RegisterMSG) */ {
 public:
  RegisterMSG();
  virtual ~RegisterMSG();

  RegisterMSG(const RegisterMSG& from);

  inline RegisterMSG& operator=(const RegisterMSG& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegisterMSG(RegisterMSG&& from) noexcept
    : RegisterMSG() {
    *this = ::std::move(from);
  }

  inline RegisterMSG& operator=(RegisterMSG&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterMSG& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterMSG* internal_default_instance() {
    return reinterpret_cast<const RegisterMSG*>(
               &_RegisterMSG_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(RegisterMSG* other);
  friend void swap(RegisterMSG& a, RegisterMSG& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegisterMSG* New() const PROTOBUF_FINAL { return New(NULL); }

  RegisterMSG* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RegisterMSG& from);
  void MergeFrom(const RegisterMSG& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RegisterMSG* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string username = 2;
  void clear_username();
  static const int kUsernameFieldNumber = 2;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string password = 3;
  void clear_password();
  static const int kPasswordFieldNumber = 3;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // int32 type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LU.RegisterMSG)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::int32 type_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsRegisterMSGImpl();
};
// -------------------------------------------------------------------

class RegisterRSPS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.RegisterRSPS) */ {
 public:
  RegisterRSPS();
  virtual ~RegisterRSPS();

  RegisterRSPS(const RegisterRSPS& from);

  inline RegisterRSPS& operator=(const RegisterRSPS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegisterRSPS(RegisterRSPS&& from) noexcept
    : RegisterRSPS() {
    *this = ::std::move(from);
  }

  inline RegisterRSPS& operator=(RegisterRSPS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterRSPS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterRSPS* internal_default_instance() {
    return reinterpret_cast<const RegisterRSPS*>(
               &_RegisterRSPS_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(RegisterRSPS* other);
  friend void swap(RegisterRSPS& a, RegisterRSPS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegisterRSPS* New() const PROTOBUF_FINAL { return New(NULL); }

  RegisterRSPS* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RegisterRSPS& from);
  void MergeFrom(const RegisterRSPS& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RegisterRSPS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int32 type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LU.RegisterRSPS)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 type_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsRegisterRSPSImpl();
};
// -------------------------------------------------------------------

class ChatMSG : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.ChatMSG) */ {
 public:
  ChatMSG();
  virtual ~ChatMSG();

  ChatMSG(const ChatMSG& from);

  inline ChatMSG& operator=(const ChatMSG& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ChatMSG(ChatMSG&& from) noexcept
    : ChatMSG() {
    *this = ::std::move(from);
  }

  inline ChatMSG& operator=(ChatMSG&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatMSG& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ChatMSG* internal_default_instance() {
    return reinterpret_cast<const ChatMSG*>(
               &_ChatMSG_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(ChatMSG* other);
  friend void swap(ChatMSG& a, ChatMSG& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ChatMSG* New() const PROTOBUF_FINAL { return New(NULL); }

  ChatMSG* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ChatMSG& from);
  void MergeFrom(const ChatMSG& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ChatMSG* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string playname = 2;
  void clear_playname();
  static const int kPlaynameFieldNumber = 2;
  const ::std::string& playname() const;
  void set_playname(const ::std::string& value);
  #if LANG_CXX11
  void set_playname(::std::string&& value);
  #endif
  void set_playname(const char* value);
  void set_playname(const char* value, size_t size);
  ::std::string* mutable_playname();
  ::std::string* release_playname();
  void set_allocated_playname(::std::string* playname);

  // string message = 3;
  void clear_message();
  static const int kMessageFieldNumber = 3;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int32 type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LU.ChatMSG)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr playname_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 type_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsChatMSGImpl();
};
// -------------------------------------------------------------------

class ChatRSPS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.ChatRSPS) */ {
 public:
  ChatRSPS();
  virtual ~ChatRSPS();

  ChatRSPS(const ChatRSPS& from);

  inline ChatRSPS& operator=(const ChatRSPS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ChatRSPS(ChatRSPS&& from) noexcept
    : ChatRSPS() {
    *this = ::std::move(from);
  }

  inline ChatRSPS& operator=(ChatRSPS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatRSPS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ChatRSPS* internal_default_instance() {
    return reinterpret_cast<const ChatRSPS*>(
               &_ChatRSPS_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(ChatRSPS* other);
  friend void swap(ChatRSPS& a, ChatRSPS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ChatRSPS* New() const PROTOBUF_FINAL { return New(NULL); }

  ChatRSPS* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ChatRSPS& from);
  void MergeFrom(const ChatRSPS& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ChatRSPS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string playname = 2;
  void clear_playname();
  static const int kPlaynameFieldNumber = 2;
  const ::std::string& playname() const;
  void set_playname(const ::std::string& value);
  #if LANG_CXX11
  void set_playname(::std::string&& value);
  #endif
  void set_playname(const char* value);
  void set_playname(const char* value, size_t size);
  ::std::string* mutable_playname();
  ::std::string* release_playname();
  void set_allocated_playname(::std::string* playname);

  // string message = 3;
  void clear_message();
  static const int kMessageFieldNumber = 3;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int32 type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LU.ChatRSPS)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr playname_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 type_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsChatRSPSImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LoginMSG

// int32 type = 1;
inline void LoginMSG::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 LoginMSG::type() const {
  // @@protoc_insertion_point(field_get:LU.LoginMSG.type)
  return type_;
}
inline void LoginMSG::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:LU.LoginMSG.type)
}

// string username = 2;
inline void LoginMSG::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoginMSG::username() const {
  // @@protoc_insertion_point(field_get:LU.LoginMSG.username)
  return username_.GetNoArena();
}
inline void LoginMSG::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.LoginMSG.username)
}
#if LANG_CXX11
inline void LoginMSG::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.LoginMSG.username)
}
#endif
inline void LoginMSG::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.LoginMSG.username)
}
inline void LoginMSG::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.LoginMSG.username)
}
inline ::std::string* LoginMSG::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:LU.LoginMSG.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginMSG::release_username() {
  // @@protoc_insertion_point(field_release:LU.LoginMSG.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginMSG::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:LU.LoginMSG.username)
}

// string password = 3;
inline void LoginMSG::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoginMSG::password() const {
  // @@protoc_insertion_point(field_get:LU.LoginMSG.password)
  return password_.GetNoArena();
}
inline void LoginMSG::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.LoginMSG.password)
}
#if LANG_CXX11
inline void LoginMSG::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.LoginMSG.password)
}
#endif
inline void LoginMSG::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.LoginMSG.password)
}
inline void LoginMSG::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.LoginMSG.password)
}
inline ::std::string* LoginMSG::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:LU.LoginMSG.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginMSG::release_password() {
  // @@protoc_insertion_point(field_release:LU.LoginMSG.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginMSG::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:LU.LoginMSG.password)
}

// -------------------------------------------------------------------

// LoginRSPS

// int32 type = 1;
inline void LoginRSPS::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 LoginRSPS::type() const {
  // @@protoc_insertion_point(field_get:LU.LoginRSPS.type)
  return type_;
}
inline void LoginRSPS::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:LU.LoginRSPS.type)
}

// string message = 2;
inline void LoginRSPS::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoginRSPS::message() const {
  // @@protoc_insertion_point(field_get:LU.LoginRSPS.message)
  return message_.GetNoArena();
}
inline void LoginRSPS::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.LoginRSPS.message)
}
#if LANG_CXX11
inline void LoginRSPS::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.LoginRSPS.message)
}
#endif
inline void LoginRSPS::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.LoginRSPS.message)
}
inline void LoginRSPS::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.LoginRSPS.message)
}
inline ::std::string* LoginRSPS::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:LU.LoginRSPS.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginRSPS::release_message() {
  // @@protoc_insertion_point(field_release:LU.LoginRSPS.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRSPS::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:LU.LoginRSPS.message)
}

// -------------------------------------------------------------------

// RegisterMSG

// int32 type = 1;
inline void RegisterMSG::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 RegisterMSG::type() const {
  // @@protoc_insertion_point(field_get:LU.RegisterMSG.type)
  return type_;
}
inline void RegisterMSG::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:LU.RegisterMSG.type)
}

// string username = 2;
inline void RegisterMSG::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RegisterMSG::username() const {
  // @@protoc_insertion_point(field_get:LU.RegisterMSG.username)
  return username_.GetNoArena();
}
inline void RegisterMSG::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.RegisterMSG.username)
}
#if LANG_CXX11
inline void RegisterMSG::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.RegisterMSG.username)
}
#endif
inline void RegisterMSG::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.RegisterMSG.username)
}
inline void RegisterMSG::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.RegisterMSG.username)
}
inline ::std::string* RegisterMSG::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:LU.RegisterMSG.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RegisterMSG::release_username() {
  // @@protoc_insertion_point(field_release:LU.RegisterMSG.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterMSG::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:LU.RegisterMSG.username)
}

// string password = 3;
inline void RegisterMSG::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RegisterMSG::password() const {
  // @@protoc_insertion_point(field_get:LU.RegisterMSG.password)
  return password_.GetNoArena();
}
inline void RegisterMSG::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.RegisterMSG.password)
}
#if LANG_CXX11
inline void RegisterMSG::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.RegisterMSG.password)
}
#endif
inline void RegisterMSG::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.RegisterMSG.password)
}
inline void RegisterMSG::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.RegisterMSG.password)
}
inline ::std::string* RegisterMSG::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:LU.RegisterMSG.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RegisterMSG::release_password() {
  // @@protoc_insertion_point(field_release:LU.RegisterMSG.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterMSG::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:LU.RegisterMSG.password)
}

// -------------------------------------------------------------------

// RegisterRSPS

// int32 type = 1;
inline void RegisterRSPS::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 RegisterRSPS::type() const {
  // @@protoc_insertion_point(field_get:LU.RegisterRSPS.type)
  return type_;
}
inline void RegisterRSPS::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:LU.RegisterRSPS.type)
}

// string message = 2;
inline void RegisterRSPS::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RegisterRSPS::message() const {
  // @@protoc_insertion_point(field_get:LU.RegisterRSPS.message)
  return message_.GetNoArena();
}
inline void RegisterRSPS::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.RegisterRSPS.message)
}
#if LANG_CXX11
inline void RegisterRSPS::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.RegisterRSPS.message)
}
#endif
inline void RegisterRSPS::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.RegisterRSPS.message)
}
inline void RegisterRSPS::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.RegisterRSPS.message)
}
inline ::std::string* RegisterRSPS::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:LU.RegisterRSPS.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RegisterRSPS::release_message() {
  // @@protoc_insertion_point(field_release:LU.RegisterRSPS.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterRSPS::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:LU.RegisterRSPS.message)
}

// -------------------------------------------------------------------

// ChatMSG

// int32 type = 1;
inline void ChatMSG::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 ChatMSG::type() const {
  // @@protoc_insertion_point(field_get:LU.ChatMSG.type)
  return type_;
}
inline void ChatMSG::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:LU.ChatMSG.type)
}

// string playname = 2;
inline void ChatMSG::clear_playname() {
  playname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ChatMSG::playname() const {
  // @@protoc_insertion_point(field_get:LU.ChatMSG.playname)
  return playname_.GetNoArena();
}
inline void ChatMSG::set_playname(const ::std::string& value) {
  
  playname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.ChatMSG.playname)
}
#if LANG_CXX11
inline void ChatMSG::set_playname(::std::string&& value) {
  
  playname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.ChatMSG.playname)
}
#endif
inline void ChatMSG::set_playname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  playname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.ChatMSG.playname)
}
inline void ChatMSG::set_playname(const char* value, size_t size) {
  
  playname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.ChatMSG.playname)
}
inline ::std::string* ChatMSG::mutable_playname() {
  
  // @@protoc_insertion_point(field_mutable:LU.ChatMSG.playname)
  return playname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChatMSG::release_playname() {
  // @@protoc_insertion_point(field_release:LU.ChatMSG.playname)
  
  return playname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMSG::set_allocated_playname(::std::string* playname) {
  if (playname != NULL) {
    
  } else {
    
  }
  playname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), playname);
  // @@protoc_insertion_point(field_set_allocated:LU.ChatMSG.playname)
}

// string message = 3;
inline void ChatMSG::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ChatMSG::message() const {
  // @@protoc_insertion_point(field_get:LU.ChatMSG.message)
  return message_.GetNoArena();
}
inline void ChatMSG::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.ChatMSG.message)
}
#if LANG_CXX11
inline void ChatMSG::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.ChatMSG.message)
}
#endif
inline void ChatMSG::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.ChatMSG.message)
}
inline void ChatMSG::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.ChatMSG.message)
}
inline ::std::string* ChatMSG::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:LU.ChatMSG.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChatMSG::release_message() {
  // @@protoc_insertion_point(field_release:LU.ChatMSG.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMSG::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:LU.ChatMSG.message)
}

// -------------------------------------------------------------------

// ChatRSPS

// int32 type = 1;
inline void ChatRSPS::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 ChatRSPS::type() const {
  // @@protoc_insertion_point(field_get:LU.ChatRSPS.type)
  return type_;
}
inline void ChatRSPS::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:LU.ChatRSPS.type)
}

// string playname = 2;
inline void ChatRSPS::clear_playname() {
  playname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ChatRSPS::playname() const {
  // @@protoc_insertion_point(field_get:LU.ChatRSPS.playname)
  return playname_.GetNoArena();
}
inline void ChatRSPS::set_playname(const ::std::string& value) {
  
  playname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.ChatRSPS.playname)
}
#if LANG_CXX11
inline void ChatRSPS::set_playname(::std::string&& value) {
  
  playname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.ChatRSPS.playname)
}
#endif
inline void ChatRSPS::set_playname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  playname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.ChatRSPS.playname)
}
inline void ChatRSPS::set_playname(const char* value, size_t size) {
  
  playname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.ChatRSPS.playname)
}
inline ::std::string* ChatRSPS::mutable_playname() {
  
  // @@protoc_insertion_point(field_mutable:LU.ChatRSPS.playname)
  return playname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChatRSPS::release_playname() {
  // @@protoc_insertion_point(field_release:LU.ChatRSPS.playname)
  
  return playname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatRSPS::set_allocated_playname(::std::string* playname) {
  if (playname != NULL) {
    
  } else {
    
  }
  playname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), playname);
  // @@protoc_insertion_point(field_set_allocated:LU.ChatRSPS.playname)
}

// string message = 3;
inline void ChatRSPS::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ChatRSPS::message() const {
  // @@protoc_insertion_point(field_get:LU.ChatRSPS.message)
  return message_.GetNoArena();
}
inline void ChatRSPS::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.ChatRSPS.message)
}
#if LANG_CXX11
inline void ChatRSPS::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.ChatRSPS.message)
}
#endif
inline void ChatRSPS::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.ChatRSPS.message)
}
inline void ChatRSPS::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.ChatRSPS.message)
}
inline ::std::string* ChatRSPS::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:LU.ChatRSPS.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChatRSPS::release_message() {
  // @@protoc_insertion_point(field_release:LU.ChatRSPS.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatRSPS::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:LU.ChatRSPS.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace LU

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerMessageProto_2eproto__INCLUDED
