// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessageProto.proto

#ifndef PROTOBUF_ServerMessageProto_2eproto__INCLUDED
#define PROTOBUF_ServerMessageProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_ServerMessageProto_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[11];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsLoginMSGImpl();
void InitDefaultsLoginMSG();
void InitDefaultsLoginRSPSImpl();
void InitDefaultsLoginRSPS();
void InitDefaultsRegisterMSGImpl();
void InitDefaultsRegisterMSG();
void InitDefaultsRegisterRSPSImpl();
void InitDefaultsRegisterRSPS();
void InitDefaultsChatMSGImpl();
void InitDefaultsChatMSG();
void InitDefaultsChatRSPSImpl();
void InitDefaultsChatRSPS();
void InitDefaultsMatchMSGImpl();
void InitDefaultsMatchMSG();
void InitDefaultsMatchRSPSImpl();
void InitDefaultsMatchRSPS();
void InitDefaultsSCStartGameImpl();
void InitDefaultsSCStartGame();
void InitDefaultsCSFrameNotifyImpl();
void InitDefaultsCSFrameNotify();
void InitDefaultsSCFrameNotifyImpl();
void InitDefaultsSCFrameNotify();
inline void InitDefaults() {
  InitDefaultsLoginMSG();
  InitDefaultsLoginRSPS();
  InitDefaultsRegisterMSG();
  InitDefaultsRegisterRSPS();
  InitDefaultsChatMSG();
  InitDefaultsChatRSPS();
  InitDefaultsMatchMSG();
  InitDefaultsMatchRSPS();
  InitDefaultsSCStartGame();
  InitDefaultsCSFrameNotify();
  InitDefaultsSCFrameNotify();
}
}  // namespace protobuf_ServerMessageProto_2eproto
namespace LU {
class CSFrameNotify;
class CSFrameNotifyDefaultTypeInternal;
extern CSFrameNotifyDefaultTypeInternal _CSFrameNotify_default_instance_;
class ChatMSG;
class ChatMSGDefaultTypeInternal;
extern ChatMSGDefaultTypeInternal _ChatMSG_default_instance_;
class ChatRSPS;
class ChatRSPSDefaultTypeInternal;
extern ChatRSPSDefaultTypeInternal _ChatRSPS_default_instance_;
class LoginMSG;
class LoginMSGDefaultTypeInternal;
extern LoginMSGDefaultTypeInternal _LoginMSG_default_instance_;
class LoginRSPS;
class LoginRSPSDefaultTypeInternal;
extern LoginRSPSDefaultTypeInternal _LoginRSPS_default_instance_;
class MatchMSG;
class MatchMSGDefaultTypeInternal;
extern MatchMSGDefaultTypeInternal _MatchMSG_default_instance_;
class MatchRSPS;
class MatchRSPSDefaultTypeInternal;
extern MatchRSPSDefaultTypeInternal _MatchRSPS_default_instance_;
class RegisterMSG;
class RegisterMSGDefaultTypeInternal;
extern RegisterMSGDefaultTypeInternal _RegisterMSG_default_instance_;
class RegisterRSPS;
class RegisterRSPSDefaultTypeInternal;
extern RegisterRSPSDefaultTypeInternal _RegisterRSPS_default_instance_;
class SCFrameNotify;
class SCFrameNotifyDefaultTypeInternal;
extern SCFrameNotifyDefaultTypeInternal _SCFrameNotify_default_instance_;
class SCStartGame;
class SCStartGameDefaultTypeInternal;
extern SCStartGameDefaultTypeInternal _SCStartGame_default_instance_;
}  // namespace LU
namespace LU {

// ===================================================================

class LoginMSG : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.LoginMSG) */ {
 public:
  LoginMSG();
  virtual ~LoginMSG();

  LoginMSG(const LoginMSG& from);

  inline LoginMSG& operator=(const LoginMSG& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LoginMSG(LoginMSG&& from) noexcept
    : LoginMSG() {
    *this = ::std::move(from);
  }

  inline LoginMSG& operator=(LoginMSG&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginMSG& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoginMSG* internal_default_instance() {
    return reinterpret_cast<const LoginMSG*>(
               &_LoginMSG_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(LoginMSG* other);
  friend void swap(LoginMSG& a, LoginMSG& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LoginMSG* New() const PROTOBUF_FINAL { return New(NULL); }

  LoginMSG* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LoginMSG& from);
  void MergeFrom(const LoginMSG& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LoginMSG* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string username = 2;
  void clear_username();
  static const int kUsernameFieldNumber = 2;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string password = 3;
  void clear_password();
  static const int kPasswordFieldNumber = 3;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:LU.LoginMSG)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsLoginMSGImpl();
};
// -------------------------------------------------------------------

class LoginRSPS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.LoginRSPS) */ {
 public:
  LoginRSPS();
  virtual ~LoginRSPS();

  LoginRSPS(const LoginRSPS& from);

  inline LoginRSPS& operator=(const LoginRSPS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LoginRSPS(LoginRSPS&& from) noexcept
    : LoginRSPS() {
    *this = ::std::move(from);
  }

  inline LoginRSPS& operator=(LoginRSPS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRSPS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoginRSPS* internal_default_instance() {
    return reinterpret_cast<const LoginRSPS*>(
               &_LoginRSPS_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(LoginRSPS* other);
  friend void swap(LoginRSPS& a, LoginRSPS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LoginRSPS* New() const PROTOBUF_FINAL { return New(NULL); }

  LoginRSPS* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LoginRSPS& from);
  void MergeFrom(const LoginRSPS& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LoginRSPS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:LU.LoginRSPS)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsLoginRSPSImpl();
};
// -------------------------------------------------------------------

class RegisterMSG : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.RegisterMSG) */ {
 public:
  RegisterMSG();
  virtual ~RegisterMSG();

  RegisterMSG(const RegisterMSG& from);

  inline RegisterMSG& operator=(const RegisterMSG& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegisterMSG(RegisterMSG&& from) noexcept
    : RegisterMSG() {
    *this = ::std::move(from);
  }

  inline RegisterMSG& operator=(RegisterMSG&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterMSG& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterMSG* internal_default_instance() {
    return reinterpret_cast<const RegisterMSG*>(
               &_RegisterMSG_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(RegisterMSG* other);
  friend void swap(RegisterMSG& a, RegisterMSG& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegisterMSG* New() const PROTOBUF_FINAL { return New(NULL); }

  RegisterMSG* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RegisterMSG& from);
  void MergeFrom(const RegisterMSG& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RegisterMSG* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string username = 2;
  void clear_username();
  static const int kUsernameFieldNumber = 2;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string password = 3;
  void clear_password();
  static const int kPasswordFieldNumber = 3;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:LU.RegisterMSG)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsRegisterMSGImpl();
};
// -------------------------------------------------------------------

class RegisterRSPS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.RegisterRSPS) */ {
 public:
  RegisterRSPS();
  virtual ~RegisterRSPS();

  RegisterRSPS(const RegisterRSPS& from);

  inline RegisterRSPS& operator=(const RegisterRSPS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegisterRSPS(RegisterRSPS&& from) noexcept
    : RegisterRSPS() {
    *this = ::std::move(from);
  }

  inline RegisterRSPS& operator=(RegisterRSPS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterRSPS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterRSPS* internal_default_instance() {
    return reinterpret_cast<const RegisterRSPS*>(
               &_RegisterRSPS_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(RegisterRSPS* other);
  friend void swap(RegisterRSPS& a, RegisterRSPS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegisterRSPS* New() const PROTOBUF_FINAL { return New(NULL); }

  RegisterRSPS* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RegisterRSPS& from);
  void MergeFrom(const RegisterRSPS& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RegisterRSPS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:LU.RegisterRSPS)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsRegisterRSPSImpl();
};
// -------------------------------------------------------------------

class ChatMSG : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.ChatMSG) */ {
 public:
  ChatMSG();
  virtual ~ChatMSG();

  ChatMSG(const ChatMSG& from);

  inline ChatMSG& operator=(const ChatMSG& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ChatMSG(ChatMSG&& from) noexcept
    : ChatMSG() {
    *this = ::std::move(from);
  }

  inline ChatMSG& operator=(ChatMSG&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatMSG& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ChatMSG* internal_default_instance() {
    return reinterpret_cast<const ChatMSG*>(
               &_ChatMSG_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(ChatMSG* other);
  friend void swap(ChatMSG& a, ChatMSG& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ChatMSG* New() const PROTOBUF_FINAL { return New(NULL); }

  ChatMSG* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ChatMSG& from);
  void MergeFrom(const ChatMSG& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ChatMSG* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 3;
  void clear_message();
  static const int kMessageFieldNumber = 3;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int32 uin = 2;
  void clear_uin();
  static const int kUinFieldNumber = 2;
  ::google::protobuf::int32 uin() const;
  void set_uin(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LU.ChatMSG)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 uin_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsChatMSGImpl();
};
// -------------------------------------------------------------------

class ChatRSPS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.ChatRSPS) */ {
 public:
  ChatRSPS();
  virtual ~ChatRSPS();

  ChatRSPS(const ChatRSPS& from);

  inline ChatRSPS& operator=(const ChatRSPS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ChatRSPS(ChatRSPS&& from) noexcept
    : ChatRSPS() {
    *this = ::std::move(from);
  }

  inline ChatRSPS& operator=(ChatRSPS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatRSPS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ChatRSPS* internal_default_instance() {
    return reinterpret_cast<const ChatRSPS*>(
               &_ChatRSPS_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(ChatRSPS* other);
  friend void swap(ChatRSPS& a, ChatRSPS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ChatRSPS* New() const PROTOBUF_FINAL { return New(NULL); }

  ChatRSPS* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ChatRSPS& from);
  void MergeFrom(const ChatRSPS& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ChatRSPS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 3;
  void clear_message();
  static const int kMessageFieldNumber = 3;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int32 uin = 2;
  void clear_uin();
  static const int kUinFieldNumber = 2;
  ::google::protobuf::int32 uin() const;
  void set_uin(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LU.ChatRSPS)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 uin_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsChatRSPSImpl();
};
// -------------------------------------------------------------------

class MatchMSG : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.MatchMSG) */ {
 public:
  MatchMSG();
  virtual ~MatchMSG();

  MatchMSG(const MatchMSG& from);

  inline MatchMSG& operator=(const MatchMSG& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MatchMSG(MatchMSG&& from) noexcept
    : MatchMSG() {
    *this = ::std::move(from);
  }

  inline MatchMSG& operator=(MatchMSG&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MatchMSG& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MatchMSG* internal_default_instance() {
    return reinterpret_cast<const MatchMSG*>(
               &_MatchMSG_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(MatchMSG* other);
  friend void swap(MatchMSG& a, MatchMSG& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MatchMSG* New() const PROTOBUF_FINAL { return New(NULL); }

  MatchMSG* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MatchMSG& from);
  void MergeFrom(const MatchMSG& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MatchMSG* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string role = 2;
  void clear_role();
  static const int kRoleFieldNumber = 2;
  const ::std::string& role() const;
  void set_role(const ::std::string& value);
  #if LANG_CXX11
  void set_role(::std::string&& value);
  #endif
  void set_role(const char* value);
  void set_role(const char* value, size_t size);
  ::std::string* mutable_role();
  ::std::string* release_role();
  void set_allocated_role(::std::string* role);

  // @@protoc_insertion_point(class_scope:LU.MatchMSG)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr role_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsMatchMSGImpl();
};
// -------------------------------------------------------------------

class MatchRSPS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.MatchRSPS) */ {
 public:
  MatchRSPS();
  virtual ~MatchRSPS();

  MatchRSPS(const MatchRSPS& from);

  inline MatchRSPS& operator=(const MatchRSPS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MatchRSPS(MatchRSPS&& from) noexcept
    : MatchRSPS() {
    *this = ::std::move(from);
  }

  inline MatchRSPS& operator=(MatchRSPS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MatchRSPS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MatchRSPS* internal_default_instance() {
    return reinterpret_cast<const MatchRSPS*>(
               &_MatchRSPS_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(MatchRSPS* other);
  friend void swap(MatchRSPS& a, MatchRSPS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MatchRSPS* New() const PROTOBUF_FINAL { return New(NULL); }

  MatchRSPS* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MatchRSPS& from);
  void MergeFrom(const MatchRSPS& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MatchRSPS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 uin = 2;
  void clear_uin();
  static const int kUinFieldNumber = 2;
  ::google::protobuf::int32 uin() const;
  void set_uin(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LU.MatchRSPS)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 uin_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsMatchRSPSImpl();
};
// -------------------------------------------------------------------

class SCStartGame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.SCStartGame) */ {
 public:
  SCStartGame();
  virtual ~SCStartGame();

  SCStartGame(const SCStartGame& from);

  inline SCStartGame& operator=(const SCStartGame& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SCStartGame(SCStartGame&& from) noexcept
    : SCStartGame() {
    *this = ::std::move(from);
  }

  inline SCStartGame& operator=(SCStartGame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SCStartGame& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SCStartGame* internal_default_instance() {
    return reinterpret_cast<const SCStartGame*>(
               &_SCStartGame_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(SCStartGame* other);
  friend void swap(SCStartGame& a, SCStartGame& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SCStartGame* New() const PROTOBUF_FINAL { return New(NULL); }

  SCStartGame* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SCStartGame& from);
  void MergeFrom(const SCStartGame& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SCStartGame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 uins = 2;
  int uins_size() const;
  void clear_uins();
  static const int kUinsFieldNumber = 2;
  ::google::protobuf::int32 uins(int index) const;
  void set_uins(int index, ::google::protobuf::int32 value);
  void add_uins(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      uins() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_uins();

  // @@protoc_insertion_point(class_scope:LU.SCStartGame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > uins_;
  mutable int _uins_cached_byte_size_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsSCStartGameImpl();
};
// -------------------------------------------------------------------

class CSFrameNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.CSFrameNotify) */ {
 public:
  CSFrameNotify();
  virtual ~CSFrameNotify();

  CSFrameNotify(const CSFrameNotify& from);

  inline CSFrameNotify& operator=(const CSFrameNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CSFrameNotify(CSFrameNotify&& from) noexcept
    : CSFrameNotify() {
    *this = ::std::move(from);
  }

  inline CSFrameNotify& operator=(CSFrameNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSFrameNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CSFrameNotify* internal_default_instance() {
    return reinterpret_cast<const CSFrameNotify*>(
               &_CSFrameNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(CSFrameNotify* other);
  friend void swap(CSFrameNotify& a, CSFrameNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CSFrameNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  CSFrameNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CSFrameNotify& from);
  void MergeFrom(const CSFrameNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CSFrameNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 keys = 3;
  int keys_size() const;
  void clear_keys();
  static const int kKeysFieldNumber = 3;
  ::google::protobuf::int32 keys(int index) const;
  void set_keys(int index, ::google::protobuf::int32 value);
  void add_keys(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      keys() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_keys();

  // int32 uin = 2;
  void clear_uin();
  static const int kUinFieldNumber = 2;
  ::google::protobuf::int32 uin() const;
  void set_uin(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LU.CSFrameNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > keys_;
  mutable int _keys_cached_byte_size_;
  ::google::protobuf::int32 uin_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsCSFrameNotifyImpl();
};
// -------------------------------------------------------------------

class SCFrameNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LU.SCFrameNotify) */ {
 public:
  SCFrameNotify();
  virtual ~SCFrameNotify();

  SCFrameNotify(const SCFrameNotify& from);

  inline SCFrameNotify& operator=(const SCFrameNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SCFrameNotify(SCFrameNotify&& from) noexcept
    : SCFrameNotify() {
    *this = ::std::move(from);
  }

  inline SCFrameNotify& operator=(SCFrameNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SCFrameNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SCFrameNotify* internal_default_instance() {
    return reinterpret_cast<const SCFrameNotify*>(
               &_SCFrameNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(SCFrameNotify* other);
  friend void swap(SCFrameNotify& a, SCFrameNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SCFrameNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  SCFrameNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SCFrameNotify& from);
  void MergeFrom(const SCFrameNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SCFrameNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .LU.CSFrameNotify keys = 2;
  int keys_size() const;
  void clear_keys();
  static const int kKeysFieldNumber = 2;
  const ::LU::CSFrameNotify& keys(int index) const;
  ::LU::CSFrameNotify* mutable_keys(int index);
  ::LU::CSFrameNotify* add_keys();
  ::google::protobuf::RepeatedPtrField< ::LU::CSFrameNotify >*
      mutable_keys();
  const ::google::protobuf::RepeatedPtrField< ::LU::CSFrameNotify >&
      keys() const;

  // int32 currentFrame = 3;
  void clear_currentframe();
  static const int kCurrentFrameFieldNumber = 3;
  ::google::protobuf::int32 currentframe() const;
  void set_currentframe(::google::protobuf::int32 value);

  // int32 nextFrame = 4;
  void clear_nextframe();
  static const int kNextFrameFieldNumber = 4;
  ::google::protobuf::int32 nextframe() const;
  void set_nextframe(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LU.SCFrameNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::LU::CSFrameNotify > keys_;
  ::google::protobuf::int32 currentframe_;
  ::google::protobuf::int32 nextframe_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMessageProto_2eproto::TableStruct;
  friend void ::protobuf_ServerMessageProto_2eproto::InitDefaultsSCFrameNotifyImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LoginMSG

// string username = 2;
inline void LoginMSG::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoginMSG::username() const {
  // @@protoc_insertion_point(field_get:LU.LoginMSG.username)
  return username_.GetNoArena();
}
inline void LoginMSG::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.LoginMSG.username)
}
#if LANG_CXX11
inline void LoginMSG::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.LoginMSG.username)
}
#endif
inline void LoginMSG::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.LoginMSG.username)
}
inline void LoginMSG::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.LoginMSG.username)
}
inline ::std::string* LoginMSG::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:LU.LoginMSG.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginMSG::release_username() {
  // @@protoc_insertion_point(field_release:LU.LoginMSG.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginMSG::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:LU.LoginMSG.username)
}

// string password = 3;
inline void LoginMSG::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoginMSG::password() const {
  // @@protoc_insertion_point(field_get:LU.LoginMSG.password)
  return password_.GetNoArena();
}
inline void LoginMSG::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.LoginMSG.password)
}
#if LANG_CXX11
inline void LoginMSG::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.LoginMSG.password)
}
#endif
inline void LoginMSG::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.LoginMSG.password)
}
inline void LoginMSG::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.LoginMSG.password)
}
inline ::std::string* LoginMSG::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:LU.LoginMSG.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginMSG::release_password() {
  // @@protoc_insertion_point(field_release:LU.LoginMSG.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginMSG::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:LU.LoginMSG.password)
}

// -------------------------------------------------------------------

// LoginRSPS

// string message = 2;
inline void LoginRSPS::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoginRSPS::message() const {
  // @@protoc_insertion_point(field_get:LU.LoginRSPS.message)
  return message_.GetNoArena();
}
inline void LoginRSPS::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.LoginRSPS.message)
}
#if LANG_CXX11
inline void LoginRSPS::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.LoginRSPS.message)
}
#endif
inline void LoginRSPS::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.LoginRSPS.message)
}
inline void LoginRSPS::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.LoginRSPS.message)
}
inline ::std::string* LoginRSPS::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:LU.LoginRSPS.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginRSPS::release_message() {
  // @@protoc_insertion_point(field_release:LU.LoginRSPS.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRSPS::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:LU.LoginRSPS.message)
}

// -------------------------------------------------------------------

// RegisterMSG

// string username = 2;
inline void RegisterMSG::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RegisterMSG::username() const {
  // @@protoc_insertion_point(field_get:LU.RegisterMSG.username)
  return username_.GetNoArena();
}
inline void RegisterMSG::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.RegisterMSG.username)
}
#if LANG_CXX11
inline void RegisterMSG::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.RegisterMSG.username)
}
#endif
inline void RegisterMSG::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.RegisterMSG.username)
}
inline void RegisterMSG::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.RegisterMSG.username)
}
inline ::std::string* RegisterMSG::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:LU.RegisterMSG.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RegisterMSG::release_username() {
  // @@protoc_insertion_point(field_release:LU.RegisterMSG.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterMSG::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:LU.RegisterMSG.username)
}

// string password = 3;
inline void RegisterMSG::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RegisterMSG::password() const {
  // @@protoc_insertion_point(field_get:LU.RegisterMSG.password)
  return password_.GetNoArena();
}
inline void RegisterMSG::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.RegisterMSG.password)
}
#if LANG_CXX11
inline void RegisterMSG::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.RegisterMSG.password)
}
#endif
inline void RegisterMSG::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.RegisterMSG.password)
}
inline void RegisterMSG::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.RegisterMSG.password)
}
inline ::std::string* RegisterMSG::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:LU.RegisterMSG.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RegisterMSG::release_password() {
  // @@protoc_insertion_point(field_release:LU.RegisterMSG.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterMSG::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:LU.RegisterMSG.password)
}

// -------------------------------------------------------------------

// RegisterRSPS

// string message = 2;
inline void RegisterRSPS::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RegisterRSPS::message() const {
  // @@protoc_insertion_point(field_get:LU.RegisterRSPS.message)
  return message_.GetNoArena();
}
inline void RegisterRSPS::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.RegisterRSPS.message)
}
#if LANG_CXX11
inline void RegisterRSPS::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.RegisterRSPS.message)
}
#endif
inline void RegisterRSPS::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.RegisterRSPS.message)
}
inline void RegisterRSPS::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.RegisterRSPS.message)
}
inline ::std::string* RegisterRSPS::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:LU.RegisterRSPS.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RegisterRSPS::release_message() {
  // @@protoc_insertion_point(field_release:LU.RegisterRSPS.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterRSPS::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:LU.RegisterRSPS.message)
}

// -------------------------------------------------------------------

// ChatMSG

// int32 uin = 2;
inline void ChatMSG::clear_uin() {
  uin_ = 0;
}
inline ::google::protobuf::int32 ChatMSG::uin() const {
  // @@protoc_insertion_point(field_get:LU.ChatMSG.uin)
  return uin_;
}
inline void ChatMSG::set_uin(::google::protobuf::int32 value) {
  
  uin_ = value;
  // @@protoc_insertion_point(field_set:LU.ChatMSG.uin)
}

// string message = 3;
inline void ChatMSG::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ChatMSG::message() const {
  // @@protoc_insertion_point(field_get:LU.ChatMSG.message)
  return message_.GetNoArena();
}
inline void ChatMSG::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.ChatMSG.message)
}
#if LANG_CXX11
inline void ChatMSG::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.ChatMSG.message)
}
#endif
inline void ChatMSG::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.ChatMSG.message)
}
inline void ChatMSG::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.ChatMSG.message)
}
inline ::std::string* ChatMSG::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:LU.ChatMSG.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChatMSG::release_message() {
  // @@protoc_insertion_point(field_release:LU.ChatMSG.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMSG::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:LU.ChatMSG.message)
}

// -------------------------------------------------------------------

// ChatRSPS

// int32 uin = 2;
inline void ChatRSPS::clear_uin() {
  uin_ = 0;
}
inline ::google::protobuf::int32 ChatRSPS::uin() const {
  // @@protoc_insertion_point(field_get:LU.ChatRSPS.uin)
  return uin_;
}
inline void ChatRSPS::set_uin(::google::protobuf::int32 value) {
  
  uin_ = value;
  // @@protoc_insertion_point(field_set:LU.ChatRSPS.uin)
}

// string message = 3;
inline void ChatRSPS::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ChatRSPS::message() const {
  // @@protoc_insertion_point(field_get:LU.ChatRSPS.message)
  return message_.GetNoArena();
}
inline void ChatRSPS::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.ChatRSPS.message)
}
#if LANG_CXX11
inline void ChatRSPS::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.ChatRSPS.message)
}
#endif
inline void ChatRSPS::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.ChatRSPS.message)
}
inline void ChatRSPS::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.ChatRSPS.message)
}
inline ::std::string* ChatRSPS::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:LU.ChatRSPS.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChatRSPS::release_message() {
  // @@protoc_insertion_point(field_release:LU.ChatRSPS.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatRSPS::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:LU.ChatRSPS.message)
}

// -------------------------------------------------------------------

// MatchMSG

// string role = 2;
inline void MatchMSG::clear_role() {
  role_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MatchMSG::role() const {
  // @@protoc_insertion_point(field_get:LU.MatchMSG.role)
  return role_.GetNoArena();
}
inline void MatchMSG::set_role(const ::std::string& value) {
  
  role_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LU.MatchMSG.role)
}
#if LANG_CXX11
inline void MatchMSG::set_role(::std::string&& value) {
  
  role_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LU.MatchMSG.role)
}
#endif
inline void MatchMSG::set_role(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  role_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LU.MatchMSG.role)
}
inline void MatchMSG::set_role(const char* value, size_t size) {
  
  role_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LU.MatchMSG.role)
}
inline ::std::string* MatchMSG::mutable_role() {
  
  // @@protoc_insertion_point(field_mutable:LU.MatchMSG.role)
  return role_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MatchMSG::release_role() {
  // @@protoc_insertion_point(field_release:LU.MatchMSG.role)
  
  return role_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MatchMSG::set_allocated_role(::std::string* role) {
  if (role != NULL) {
    
  } else {
    
  }
  role_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), role);
  // @@protoc_insertion_point(field_set_allocated:LU.MatchMSG.role)
}

// -------------------------------------------------------------------

// MatchRSPS

// int32 uin = 2;
inline void MatchRSPS::clear_uin() {
  uin_ = 0;
}
inline ::google::protobuf::int32 MatchRSPS::uin() const {
  // @@protoc_insertion_point(field_get:LU.MatchRSPS.uin)
  return uin_;
}
inline void MatchRSPS::set_uin(::google::protobuf::int32 value) {
  
  uin_ = value;
  // @@protoc_insertion_point(field_set:LU.MatchRSPS.uin)
}

// -------------------------------------------------------------------

// SCStartGame

// repeated int32 uins = 2;
inline int SCStartGame::uins_size() const {
  return uins_.size();
}
inline void SCStartGame::clear_uins() {
  uins_.Clear();
}
inline ::google::protobuf::int32 SCStartGame::uins(int index) const {
  // @@protoc_insertion_point(field_get:LU.SCStartGame.uins)
  return uins_.Get(index);
}
inline void SCStartGame::set_uins(int index, ::google::protobuf::int32 value) {
  uins_.Set(index, value);
  // @@protoc_insertion_point(field_set:LU.SCStartGame.uins)
}
inline void SCStartGame::add_uins(::google::protobuf::int32 value) {
  uins_.Add(value);
  // @@protoc_insertion_point(field_add:LU.SCStartGame.uins)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SCStartGame::uins() const {
  // @@protoc_insertion_point(field_list:LU.SCStartGame.uins)
  return uins_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SCStartGame::mutable_uins() {
  // @@protoc_insertion_point(field_mutable_list:LU.SCStartGame.uins)
  return &uins_;
}

// -------------------------------------------------------------------

// CSFrameNotify

// int32 uin = 2;
inline void CSFrameNotify::clear_uin() {
  uin_ = 0;
}
inline ::google::protobuf::int32 CSFrameNotify::uin() const {
  // @@protoc_insertion_point(field_get:LU.CSFrameNotify.uin)
  return uin_;
}
inline void CSFrameNotify::set_uin(::google::protobuf::int32 value) {
  
  uin_ = value;
  // @@protoc_insertion_point(field_set:LU.CSFrameNotify.uin)
}

// repeated int32 keys = 3;
inline int CSFrameNotify::keys_size() const {
  return keys_.size();
}
inline void CSFrameNotify::clear_keys() {
  keys_.Clear();
}
inline ::google::protobuf::int32 CSFrameNotify::keys(int index) const {
  // @@protoc_insertion_point(field_get:LU.CSFrameNotify.keys)
  return keys_.Get(index);
}
inline void CSFrameNotify::set_keys(int index, ::google::protobuf::int32 value) {
  keys_.Set(index, value);
  // @@protoc_insertion_point(field_set:LU.CSFrameNotify.keys)
}
inline void CSFrameNotify::add_keys(::google::protobuf::int32 value) {
  keys_.Add(value);
  // @@protoc_insertion_point(field_add:LU.CSFrameNotify.keys)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
CSFrameNotify::keys() const {
  // @@protoc_insertion_point(field_list:LU.CSFrameNotify.keys)
  return keys_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
CSFrameNotify::mutable_keys() {
  // @@protoc_insertion_point(field_mutable_list:LU.CSFrameNotify.keys)
  return &keys_;
}

// -------------------------------------------------------------------

// SCFrameNotify

// repeated .LU.CSFrameNotify keys = 2;
inline int SCFrameNotify::keys_size() const {
  return keys_.size();
}
inline void SCFrameNotify::clear_keys() {
  keys_.Clear();
}
inline const ::LU::CSFrameNotify& SCFrameNotify::keys(int index) const {
  // @@protoc_insertion_point(field_get:LU.SCFrameNotify.keys)
  return keys_.Get(index);
}
inline ::LU::CSFrameNotify* SCFrameNotify::mutable_keys(int index) {
  // @@protoc_insertion_point(field_mutable:LU.SCFrameNotify.keys)
  return keys_.Mutable(index);
}
inline ::LU::CSFrameNotify* SCFrameNotify::add_keys() {
  // @@protoc_insertion_point(field_add:LU.SCFrameNotify.keys)
  return keys_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::LU::CSFrameNotify >*
SCFrameNotify::mutable_keys() {
  // @@protoc_insertion_point(field_mutable_list:LU.SCFrameNotify.keys)
  return &keys_;
}
inline const ::google::protobuf::RepeatedPtrField< ::LU::CSFrameNotify >&
SCFrameNotify::keys() const {
  // @@protoc_insertion_point(field_list:LU.SCFrameNotify.keys)
  return keys_;
}

// int32 currentFrame = 3;
inline void SCFrameNotify::clear_currentframe() {
  currentframe_ = 0;
}
inline ::google::protobuf::int32 SCFrameNotify::currentframe() const {
  // @@protoc_insertion_point(field_get:LU.SCFrameNotify.currentFrame)
  return currentframe_;
}
inline void SCFrameNotify::set_currentframe(::google::protobuf::int32 value) {
  
  currentframe_ = value;
  // @@protoc_insertion_point(field_set:LU.SCFrameNotify.currentFrame)
}

// int32 nextFrame = 4;
inline void SCFrameNotify::clear_nextframe() {
  nextframe_ = 0;
}
inline ::google::protobuf::int32 SCFrameNotify::nextframe() const {
  // @@protoc_insertion_point(field_get:LU.SCFrameNotify.nextFrame)
  return nextframe_;
}
inline void SCFrameNotify::set_nextframe(::google::protobuf::int32 value) {
  
  nextframe_ = value;
  // @@protoc_insertion_point(field_set:LU.SCFrameNotify.nextFrame)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace LU

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerMessageProto_2eproto__INCLUDED
